import { AssignmentOutlined } from '@material-ui/icons';

export const ADMIN_SECTION_MENU = [
    {'text': 'Lead Menu', 'link': '/viewleads', 'page': 'Leads', 'icon': <AssignmentOutlined />},
    // {'text': 'Relationships', 'link': '/admin/relationships/list', 'page': 'relationships', 'icon': <SupervisorAccountIcon />},
    // {'text': 'Graphs', 'link': '/admin/stats', 'page': 'stats', 'icon': <AssessmentIcon />},
    // {'text': 'Reports', 'link': '/admin/revenue/list', 'page': 'revenue', 'icon': <AssessmentIcon />},
    // {'text': 'Users', 'link': '/admin/users/list', 'page': 'userList', 'icon': <PeopleIcon />},
    // {'text': 'Employers', 'link': '/admin/user/employerslist', 'page': 'employerslist', 'icon': <BusinessIcon />},
    // {'text': 'Projects', 'link': '/admin/projects/list', 'page': 'projectList', 'icon': <AssignmentIcon />},
    // {'text': 'Contests', 'link': '/admin/contests/list', 'page': 'contestList', 'icon': <AssignmentIcon />},
    // {'text': 'Proposals', 'link': '/admin/proposals/list', 'page': 'proposalsList', 'icon': <AssignmentTurnedInIcon />},
    // {'text': 'Workstreams', 'link': '/admin/workstreams/list', 'page': 'workstreamList', 'icon': <AssignmentIcon />},
    // {'text': 'Services', 'link': '/admin/services/list', 'page': 'servicesList', 'icon': <SupervisorAccountIcon />},
    // {'text': 'Cancel Orders', 'link': '/admin/cancelorder/list', 'page': 'cancelorderList', 'icon': <CancelIcon />},
    // {'text': 'Admin Messages', 'link': '/admin/adminmessages/list', 'page': 'adminmessages', 'icon': <SupervisorAccountIcon />},
    // {'text': 'Recent Messages', 'link': '/admin/recentmessages/list', 'page': 'recentmessages', 'icon': <SupervisorAccountIcon />},
    // {'text': 'Refunds', 'link': '/admin/refunds/list', 'page': 'refundList', 'icon': <SettingsBackupRestoreIcon />},
    // {'text': 'Deposits', 'link': '/admin/deposits/list', 'page': 'depositList', 'icon': <AccountBalanceIcon />},
    // {'text': 'Invoices', 'link': '/admin/invoices/list', 'page': 'invoicesList', 'icon': <ReceiptIcon />},
    // {'text': 'Payouts', 'link': '/admin/withdrawals/list', 'page': 'withdrawalList', 'icon': <PaymentIcon />},
    // {'text': 'Orders', 'link': '/admin/orders/list', 'page': 'orderList', 'icon': <ReorderIcon />},
    // {'text': 'User Actions', 'link': '/admin/useractions/list', 'page': 'useractionsList', 'icon': <ReceiptIcon />},
    // {'text': 'Partial Payments', 'link': '/admin/partialpayment/list', 'page': 'partialpaymentsList', 'icon': <ReorderIcon />},
    // {'text': 'Memberships', 'link': '/admin/membership/list', 'page': 'membershipList', 'icon': <CardMembershipIcon />},
    // {'text': 'Membership Plans', 'link': '/admin/membershipplans/list', 'page': 'membershipplansList', 'icon': <CardMembershipIcon />},
    // {'text': 'Discount', 'link': '/admin/discount/list', 'page': 'discount', 'icon': <CardMembershipIcon />},
    // {'text': 'Bank Accounts', 'link': '/admin/bankinfo/list', 'page': 'bankinfoList','icon': <AccountBalanceIcon />},
    // {'text': 'Paypal Accounts', 'link': '/admin/paypalinfo/list', 'page': 'paypalinfoList','icon': <AccountBalanceIcon />},
    // {'text': 'Payoneer Accounts', 'link': '/admin/payoneerinfo/list', 'page': 'payoneerInfoList','icon': <AccountBalanceIcon />},
    // {'text': 'Skills', 'link': '/admin/skills/list', 'page': 'skillsList','icon': <CardMembershipIcon />},
    // {'text': 'Service Sale', 'link': '/admin/servicesale/list', 'page': 'servicesaleList','icon': <EqualizerIcon />},
    // {'text': 'Payment Sources', 'link': '/admin/paymentsources/list', 'page': 'paymentSourceList','icon': <EuroSymbolIcon />},
    // {'text': 'Blocked Users', 'link': '/admin/blockedusers/list', 'page': 'blockedUsersList','icon': <BlockIcon />},
    // {'text': 'Skill FAQ', 'link': '/admin/skillfaq/list', 'page': '','icon': <ListAltIcon />},
    // {'text': 'Spam Keywords Detail', 'link': '/admin/spamkeywords/list', 'page': '','icon': <ListAltIcon />},
    // {'text': 'Moderators', 'link': '/admin/moderators', 'page': 'moderator','icon': <PersonAddIcon />},
]